import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AboutProvider } from "@/context/AboutContext";
import { BannerProvider } from "@/context/BannerContext";
import { MissionVisionProvider } from "@/context/MissionVisionContext";
import { RibbonProvider } from "@/context/RibbonContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hexar Demo Application",
  description: "Generated by Hexar Demo Application",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <RibbonProvider>
          <AboutProvider>
            <MissionVisionProvider>
              <BannerProvider>{children}</BannerProvider>
            </MissionVisionProvider>
          </AboutProvider>
        </RibbonProvider>
      </body>
    </html>
  );
}
